# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements.txt
        pip3 install -r dev-requirements.txt
        pip3 install requests
    - name: Extract new swift tags
      run: |
        python3 extract.py --commit
        python3 -m unittest
    - name: Push to master
      run: git push origin master
      
